[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://freelance-marketplace-backend-tvch.onrender.com/api"
  NEXT_PUBLIC_WS_URL = "wss://freelance-marketplace-backend-tvch.onrender.com"

[dev]
  command = "npm run dev"
  port = 3000 